/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEntityRouteImport } from './routes/_app/$entity'
import { Route as AppEntityIndexRouteImport } from './routes/_app/$entity/index'
import { Route as AppEntityChar126createRouteImport } from './routes/_app/$entity/~create'
import { Route as AppEntityItemIdRouteImport } from './routes/_app/$entity/$itemId'

const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntityRoute = AppEntityRouteImport.update({
  id: '/$entity',
  path: '/$entity',
  getParentRoute: () => AppRoute,
} as any)
const AppEntityIndexRoute = AppEntityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEntityRoute,
} as any)
const AppEntityChar126createRoute = AppEntityChar126createRouteImport.update({
  id: '/~create',
  path: '/~create',
  getParentRoute: () => AppEntityRoute,
} as any)
const AppEntityItemIdRoute = AppEntityItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppEntityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/config': typeof ConfigRoute
  '/$entity': typeof AppEntityRouteWithChildren
  '/$entity/$itemId': typeof AppEntityItemIdRoute
  '/$entity/~create': typeof AppEntityChar126createRoute
  '/$entity/': typeof AppEntityIndexRoute
}
export interface FileRoutesByTo {
  '/config': typeof ConfigRoute
  '/': typeof AppIndexRoute
  '/$entity/$itemId': typeof AppEntityItemIdRoute
  '/$entity/~create': typeof AppEntityChar126createRoute
  '/$entity': typeof AppEntityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/config': typeof ConfigRoute
  '/_app/$entity': typeof AppEntityRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$entity/$itemId': typeof AppEntityItemIdRoute
  '/_app/$entity/~create': typeof AppEntityChar126createRoute
  '/_app/$entity/': typeof AppEntityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/$entity'
    | '/$entity/$itemId'
    | '/$entity/~create'
    | '/$entity/'
  fileRoutesByTo: FileRoutesByTo
  to: '/config' | '/' | '/$entity/$itemId' | '/$entity/~create' | '/$entity'
  id:
    | '__root__'
    | '/_app'
    | '/config'
    | '/_app/$entity'
    | '/_app/'
    | '/_app/$entity/$itemId'
    | '/_app/$entity/~create'
    | '/_app/$entity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConfigRoute: typeof ConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$entity': {
      id: '/_app/$entity'
      path: '/$entity'
      fullPath: '/$entity'
      preLoaderRoute: typeof AppEntityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$entity/': {
      id: '/_app/$entity/'
      path: '/'
      fullPath: '/$entity/'
      preLoaderRoute: typeof AppEntityIndexRouteImport
      parentRoute: typeof AppEntityRoute
    }
    '/_app/$entity/~create': {
      id: '/_app/$entity/~create'
      path: '/~create'
      fullPath: '/$entity/~create'
      preLoaderRoute: typeof AppEntityChar126createRouteImport
      parentRoute: typeof AppEntityRoute
    }
    '/_app/$entity/$itemId': {
      id: '/_app/$entity/$itemId'
      path: '/$itemId'
      fullPath: '/$entity/$itemId'
      preLoaderRoute: typeof AppEntityItemIdRouteImport
      parentRoute: typeof AppEntityRoute
    }
  }
}

interface AppEntityRouteChildren {
  AppEntityItemIdRoute: typeof AppEntityItemIdRoute
  AppEntityChar126createRoute: typeof AppEntityChar126createRoute
  AppEntityIndexRoute: typeof AppEntityIndexRoute
}

const AppEntityRouteChildren: AppEntityRouteChildren = {
  AppEntityItemIdRoute: AppEntityItemIdRoute,
  AppEntityChar126createRoute: AppEntityChar126createRoute,
  AppEntityIndexRoute: AppEntityIndexRoute,
}

const AppEntityRouteWithChildren = AppEntityRoute._addFileChildren(
  AppEntityRouteChildren,
)

interface AppRouteChildren {
  AppEntityRoute: typeof AppEntityRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEntityRoute: AppEntityRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConfigRoute: ConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
