/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/$collection.index'
import { Route as CollectionIdRouteImport } from './routes/$collection.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/$collection/',
  path: '/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/$collection/$id',
  path: '/$collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$collection/$id': typeof CollectionIdRoute
  '/$collection/': typeof CollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$collection/$id': typeof CollectionIdRoute
  '/$collection': typeof CollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$collection/$id': typeof CollectionIdRoute
  '/$collection/': typeof CollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$collection/$id' | '/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$collection/$id' | '/$collection'
  id: '__root__' | '/' | '/$collection/$id' | '/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionIdRoute: typeof CollectionIdRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$collection/': {
      id: '/$collection/'
      path: '/$collection'
      fullPath: '/$collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$collection/$id': {
      id: '/$collection/$id'
      path: '/$collection/$id'
      fullPath: '/$collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionIdRoute: CollectionIdRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
