server {
    listen 8080;

    root /usr/share/nginx/html;

    error_page   500 502 503 504  /50x.html;

    # Public files & index.html are not cached, but have an ETag
    # generated based on their contents.
    # This enables browsers to send an If-None-Match request,
    # which nginx can answer with 304 Not Modified, resulting in no
    # content being transferred.
    # This configuration allows skipping downloads when files are
    # already cached, but since caches are always revalidated, a change
    # will be picked up immediately.
    etag on;
    # Sets cache expiry time to immediately, content can be cached, but will
    # always be revalidated with the server.
    expires 0;

    location / {
        try_files $uri @index;
    }

    location /static {
        # Build-artifacts are cached for 30 days after the last download.
        # Browsers will keep serving these files from their own caches
        # without checking in with the server.
        # This is fine, because build-artifacts contain a content-hash in
        # their filename. A new build/deployment results in a different file
        # being referenced from index.html, and thus also a different (not yet cached) file
        # being fetched by the browser.
        expires 30d;

        # After the cache has expired in the browser, the next request for the same
        # file will be an If-None-Match request, which nginx can anwser with 304 Not Modified,
        # resulting in no content being transferred.
        etag on;
    }

    location @index {
        try_files /index.html =404;
    }
}
